### ISSUE TITLE
Cannot pyinstaller on Mac OS High Sierra

### ISSUE THREAD

**Issue by davidsouza** [HewlettPackard/python-redfish-utility#3] opened 2018-03-08 21:59 UTC
Ran both:

sudo pip install pyinstaller

&&

pyinstaller rdmc-pyinstaller-mac.spec

Using the default Python install Python 2.7.10, also tried it with brew install of Python 3.6.4

Both Python versions get the same error below.
 
3993 INFO: Analyzing src/rdmc.py

Syntax error in src/rdmc.py
  File "/Users/dsouza/Development/python-redfish-utility/src/rdmc.py", line 73
     except Exception, excp:
                     ^
 SyntaxError: invalid syntax

**Comment by Yergidy** [comment] 2018-03-09 22:52
I am unable to replicate this error with the code from github. It looks like there is a python syntax error in rdmc.py. Have you modified the code in any way?

Also,
This utility was written with Python 2.7, it is not Python 3 compatible.

**Comment by Yergidy** [comment] 2018-05-10 15:12
Closing this issue. Please reopen if the issue isn't solved.

**Closed by Yergidy** 2018-05-10 15:12 UTC
